### PR TITLE
Refactory binary type, add decimal type and more

### PR DESCRIPTION
**Pull request by bzick**
**Compatibility is not broken**

### binary

Internal behavior of binary-type was changed.

- Old behavior: binary data was always encoded to base64;
- New behavior: only call of the method `binary:data()` will be encode binary data to base64.

Previous behavior has negative impact to the performance. There is about 20% performance degradation while working with gridfs. Tested on CPU: 2,9 GHz Intel Core i7.

Were added methods `binary:set_data(data)`, `binary:set_raw(raw)` the similar as `binary:data(data)`, `binary:raw(raw)`. The new methods don't have return value.

### oid

Was added method `oid:timestamp()`. Returns timestamp value from object id string.

### decimal

Was added new BSON type [decimal128](https://github.com/mongodb/specifications/blob/master/source/bson-decimal128/decimal128.rst):

```lua
local dec = cbson.decimal("1234.456")
```

Was added tests for decimal type.

### int, uint

Were added methods `int:number()`, `uint:number()`. They are returns value as lua number (the same as `tonumer(tostring(int))`).

### Relaxed JSON

Was added method `cbson.to_relaxed_json(bson)` which encodes binary BSON data as [relaxed json](https://github.com/mongodb/specifications/blob/master/source/extended-json.rst#relaxed-extended-json-example) string.

### Other

- Updated `README.md`.
- Fixed memory leak in `cbson.to_json()`.
- Fixed regex tests.
- Updated version to `1.1`

### CODE REVIEW

**Comment by isage** [comment]
Can you please add either:
* a cmake check for libbson >= 1.5.0
* version guard for decimal128
* or add minimum required version (1.5.0) of libbson to readme?

**Comment by bzick** [comment]
* Done
* `version guard `? What do you mean?
* Done

**Comment by isage** [comment]
Nevermind, cmake check is enough.
However, i did forget about relaxed json, and the minimum libbson version for this is 1.7.0

**Comment by bzick** [comment]
oh, my fault.i totally forgot about libbson version.

**Comment by isage** [comment]
Thanks!

**Pull request merged**
